name: mighty_ui_kit
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  nb_utils: ^4.0.6
  animations: 2.0.0
  http: 0.13.0
  flutter_vector_icons: 1.0.0
  cached_network_image: ^3.0.0-nullsafety
  flutter_svg: 0.21.0-nullsafety.0
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  url_launcher: 6.0.2
  share: 2.0.0
  package_info: 2.0.0
  lipsum: 1.0.1
  intl: 0.17.0

  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  google_mobile_ads: ^0.11.0+2
  firebase_remote_config: ^0.9.0-dev.0
  google_sign_in: ^5.0.0
  cloud_firestore: ^1.0.2
  google_fonts: 2.0.0

  #e-garden
  pin_entry_text_field: ^0.1.4
  carousel_slider: ^2.3.1
  percent_indicator: ^2.1.8
  image_picker: ^0.7.2

  #handyman
  flutter_rating_bar: ^3.2.0+1

  #Snippet
  image_cropper: ^1.3.1
  shimmer: ^1.1.2
  flutter_spinkit: ^4.1.2+1
  razorpay_flutter: ^1.2.3
  flutter_stripe_payment: ^0.0.12
  flutter_barcode_scanner: ^2.0.0-nullsafety.0
  quick_actions: ^0.4.0+10
  awesome_notifications: ^0.0.5+8
  onesignal_flutter: ^2.6.2
  country_pickers: ^1.3.0

  #SmartHome
  drag_select_grid_view: ^0.3.1
  pin_code_fields: ^6.0.1
  seekbar: ^0.0.2

  #MeelaBank
  fl_chart: ^0.20.1
  country_code_picker: 1.7.0
  google_maps_flutter: 2.0.1
  sliding_up_panel: ^1.0.2

  #rentHouse
  motion_tab_bar: ^0.1.5
  chips_choice: ^2.0.1
  dotted_border: ^2.0.0-nullsafety.0

  #grocery
  credit_card_field: ^1.0.2
  timeline_tile: ^1.0.0
  flutter_slidable: ^0.5.7

  #finance
  camera: ^0.8.1
  qr_code_scanner: ^0.4.0
  convex_bottom_bar: ^3.0.0
  vibration: ^1.7.3
  syncfusion_flutter_charts: ^19.1.54+1

  #InstagramStory
  story_view: 0.13.0-nullsafety.1

  #NewWidget
  fancy_drawer: 1.0.0
  animated_drawer: 0.0.4
  wave_drawer: ^0.1.1
  signature: 4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: 1.1.2
  build_runner: ^1.9.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/app/
    - images/app/abstract_icons/
    - images/eGarden/
    - images/handyman/
    - images/smartHome/
    - images/VPNApp/
    - images/widgets/materialWidgets/
    - images/widgets/materialWidgets/mwAppStructureWidgets/BottomNavigation/
    - images/widgets/materialWidgets/mwAppStructureWidgets/TabBar/
    - images/widgets/materialWidgets/mwDialogAlertPanelWidgets/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/Checkbox/
    - images/widgets/materialWidgets/mwInputSelectionWidgets/switch/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/cards/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/category/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/gridview/
    - images/widgets/materialWidgets/mwInformationDisplayWidgets/listView/
    - images/widgets/cupertinoWidgets/
    - images/widgets/paintingandeffectWidget/
    - images/LikeButton/image/
    - images/snippet/
    - images/Meela/
    - images/rentHouse/
    - images/groceryApp/
    - images/foodDelivery/
    - images/finance/
    - images/storyView/
